# Generated by Django 5.2.3 on 2025-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='style',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Life updates', 'Life updates'), ('Travel', 'Travel'), ('Personal development', 'Personal development'), ('IT', 'IT')], default='Journal', max_length=50),
        ),
    ]
