# Generated by Django 5.2.3 on 2025-07-06 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='style',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Life updates', 'Life updates'), ('Travel', 'Travel'), ('Personal development', 'Personal development'), ('IT', 'IT'), ('Football', 'Football')], default='Journal', max_length=50),
        ),
    ]
