# Generated by Django 5.2.3 on 2025-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_created_at_alter_blog_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.BooleanField(default=True),
        ),
    ]
