# Generated by Django 5.2.3 on 2025-07-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_at',
            new_name='published',
        ),
    ]
